import sys
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter


# Custom formatter to convert raw Hz into nice kHz / MHz strings
def format_freq(x, pos):
    if x >= 1_000_000:
        if x % 1_000_000 == 0:
            return f"{int(x / 1_000_000)} MHz"
        else:
            return f"{x / 1_000_000:.1f} MHz"
    else:
        return f"{int(x / 1000)} kHz"


def plot_benchmark(csv_file):
    try:
        # Read the CSV generated by the Rust benchmark
        df = pd.read_csv(csv_file)
    except Exception as e:
        print(f"Error reading {csv_file}: {e}")
        return

    # Filter to only look at the 1-byte payloads that expose the timing bug
    df = df[df["Size_Bytes"] == 1]

    if df.empty:
        print("Error: No 1-byte payload data found in the CSV.")
        return

    # Calculate Theoretical Time: 1 byte = 8 bits. Time in microseconds = (8 / Frequency) * 1,000,000
    df["Theoretical_us"] = (8.0 / df["BaudRate"]) * 1_000_000.0

    fig, ax = plt.subplots(figsize=(14, 7))

    # Define colors for Native vs WASM
    envs = df["Environment"].unique()
    colors = {"Native": "#4a90e2", "WASM": "#d0021b"}

    # ==========================================
    # Single Panel: Linear Scale (The Danger Zone)
    # ==========================================
    # We cap the linear view at 2 MHz so the anomaly hump remains highly visible
    df_zoom = df[df["BaudRate"] <= 2_000_000]

    for env in envs:
        env_data = df_zoom[df_zoom["Environment"] == env].sort_values("BaudRate")
        if not env_data.empty:
            c = colors.get(env, "black")
            ax.plot(
                env_data["BaudRate"],
                env_data["AvgRTT_us"],
                marker="o",
                markersize=5,
                linestyle="-",
                linewidth=2.5,
                color=c,
                label=f"{env} Measured Latency",
            )

    # Plot the Theoretical Baseline once
    baud_zoom = sorted(df_zoom["BaudRate"].unique())
    theo_zoom = [(8.0 / b) * 1e6 for b in baud_zoom]
    ax.plot(
        baud_zoom,
        theo_zoom,
        color="#2ecc71",
        linestyle="--",
        linewidth=2,
        label="Theoretical HW Minimum (Wire Time)",
    )

    ax.set_title(
        'SPI Latency Anomaly ("The Danger Zone" - 1 Byte Payloads)',
        fontsize=14,
        fontweight="bold",
    )
    ax.set_xlabel("SPI Frequency", fontsize=12)
    ax.set_ylabel("Average Latency per Transfer (µs)", fontsize=12)

    # Apply the nice kHz/MHz formatter to the X-axis
    ax.xaxis.set_major_formatter(FuncFormatter(format_freq))

    ax.grid(True, linestyle="--", alpha=0.7)
    ax.legend()

    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python plot_sweep.py <results.csv>")
        sys.exit(1)
    plot_benchmark(sys.argv[1])
