package my:guest;

world app {
    // Import SPI
    import wasi:spi/spi;
    
    // Import GPIO (Digital is essential for D/C and Reset pins)
    import wasi:gpio/digital@0.2.0; 
    import wasi:gpio/delay@0.2.0;   // Often needed for screen initialization sequences
    
    export run: func();
}
