[spi.sensor]
block = "SPI0"
sck = 18
mosi = 19
miso = 16
cs = 17

[spi.screen]
block = "SPI1"
sck = 10
mosi = 11
miso = 12
cs = 13

[gpio]
DC = { pin = 2, initial = "Low" }
RES = { pin = 3, initial = "High" }
VBATC = { pin = 4, initial = "High" }
VDDC = { pin = 5, initial = "High" }
