<<<<<<< HEAD
use std::fs;

use clap::Parser;
use wasmtime::{
    Config, Engine, Store,
    component::{Component, Linker},
};
use wasmtime_wasi::{
    ResourceTable, WasiCtx, WasiCtxBuilder, WasiCtxView, WasiView, p2::add_to_linker_sync,
};

use wasi_gpio::{WasiGpioCtx, WasiGpioView};
use wasi_spi::{SpiConfig, WasiSpiCtx, WasiSpiView};

use crate::policies::HostPolicy;

mod argument_parser;
mod policies;

wasmtime::component::bindgen!({
    path: "../guests/oled-screen/pacman/wit",
    world: "app",
});

struct HostState {
    ctx: WasiCtx,
    table: ResourceTable,
    spi_ctx: WasiSpiCtx,
    gpio_ctx: WasiGpioCtx,
}

impl WasiView for HostState {
    fn ctx(&mut self) -> WasiCtxView<'_> {
        WasiCtxView {
            ctx: &mut self.ctx,
            table: &mut self.table,
        }
    }
}

impl WasiSpiView for HostState {
    fn spi_ctx(&mut self) -> &mut WasiSpiCtx {
=======
#![no_std]
#![no_main]

extern crate alloc;

use defmt::info;
use embassy_executor::Spawner;
use embassy_time::Delay;
use embedded_alloc::Heap;
use wasmtime::component::{Component, HasSelf, Linker, ResourceTable};
use wasmtime::{Config, Engine, Store};
use {defmt_rtt as _, panic_probe as _};

// Import contexts and views
use delay::{DelayCtx, DelayView};
use gpio::{GpioCtx, GpioView};
use spi::{SpiCtx, SpiView};

wasmtime::component::bindgen!({
    path: "../guest/wit",
    world: "app", // Replace with your combined world name
});

const HEAP_SIZE: usize = 470 * 1024;

#[global_allocator]
static HEAP: Heap = Heap::empty();

// Import the macro generated by build.rs!
include!(concat!(env!("OUT_DIR"), "/hardware_policy.rs"));

// --- Host State ---
pub struct HostState {
    pub spi_ctx: SpiCtx,
    pub gpio_ctx: GpioCtx,
    pub delay_ctx: DelayCtx,
}

impl my::debug::logging::Host for HostState {
    fn log(&mut self, msg: alloc::string::String) {
        defmt::info!("[Guest] {}", msg.as_str());
    }
}

impl SpiView for HostState {
    fn spi_ctx(&mut self) -> &mut SpiCtx {
>>>>>>> pico/main
        &mut self.spi_ctx
    }
}

<<<<<<< HEAD
impl WasiGpioView for HostState {
    fn gpio_ctx(&mut self) -> &mut WasiGpioCtx {
        &mut self.gpio_ctx
    }

    fn table(&mut self) -> &mut ResourceTable {
        &mut self.table
    }
}

fn main() -> anyhow::Result<()> {
    let args = argument_parser::HostArguments::parse();

    let policy_content = fs::read_to_string(&args.policy_file)
        .map_err(|e| anyhow::anyhow!("Failed to read policy file: {}", e))?;

    let policy: HostPolicy = toml::from_str(&policy_content)
        .map_err(|e| anyhow::anyhow!("Failed to parse TOML: {}", e))?;

    let spi_configs: Vec<SpiConfig> = policy
        .wasi
        .spi
        .into_iter()
        .map(|cfg| SpiConfig {
            virtual_name: cfg.virtual_name,
            physical_path: cfg.physical_path,
        })
        .collect();

    let spi_ctx = WasiSpiCtx::from_configs(spi_configs)?;

    let gpio_config = wasi_gpio::policies::Config {
        policy_file: args.policy_file,
        component: args.component_path.clone(),
    };

    let policies = gpio_config.get_policies();
    let gpio_ctx = WasiGpioCtx::new(policies);

    let state = HostState {
        ctx: WasiCtxBuilder::new().inherit_stdio().build(),
        table: ResourceTable::new(),
        spi_ctx,
        gpio_ctx,
    };

    let mut config = Config::new();
    config.wasm_component_model(true);
    let engine = Engine::new(&config)?;
    let mut linker = Linker::new(&engine);

    add_to_linker_sync(&mut linker)?;

    wasi_spi::add_to_linker(&mut linker)?;

    wasi_gpio::add_to_linker(&mut linker)?;

    let mut store = Store::new(&engine, state);
    let component = Component::from_file(&engine, &args.component_path)?;

    let app = App::instantiate(&mut store, &component, &linker)?;

    println!("Host: Calling guest run()...");
    app.call_run(&mut store)?;
    println!("Host: Guest finished.");

    Ok(())
=======
impl GpioView for HostState {
    fn gpio_ctx(&mut self) -> &mut GpioCtx {
        &mut self.gpio_ctx
    }
}

impl DelayView for HostState {
    fn delay_ctx(&mut self) -> &mut DelayCtx {
        &mut self.delay_ctx
    }
}

// --- Wasmtime TLS Hooks ---
static mut TLS_PTR: *mut u8 = core::ptr::null_mut();
#[unsafe(no_mangle)]
pub extern "C" fn wasmtime_tls_get() -> *mut u8 {
    unsafe { TLS_PTR }
}
#[unsafe(no_mangle)]
pub extern "C" fn wasmtime_tls_set(ptr: *mut u8) {
    unsafe {
        TLS_PTR = ptr;
    }
}

#[embassy_executor::main]
async fn main(_spawner: Spawner) {
    let p = embassy_rp::init(Default::default());

    // Initialize Heap
    {
        use core::mem::MaybeUninit;
        static mut HEAP_MEM: [MaybeUninit<u8>; HEAP_SIZE] = [MaybeUninit::uninit(); HEAP_SIZE];
        unsafe { HEAP.init(core::ptr::addr_of_mut!(HEAP_MEM) as usize, HEAP_SIZE) }
    }

    info!("Heap initialized.");

    let mut config = Config::new();
    config.target("pulley32").unwrap();
    config.wasm_component_model(true);
    config.gc_support(false);
    config.signals_based_traps(false);
    config.memory_init_cow(false);
    config.memory_guard_size(0);
    config.memory_reservation(0);
    config.max_wasm_stack(16 * 1024);
    config.memory_reservation_for_growth(0);

    let engine = Engine::new(&config).expect("Engine failed");

    // ====================================================
    // Dynamically expand hardware pins based on policy.toml
    // ====================================================

    let (spi_hardware, gpio_map) = configure_hardware!(p);

    // Construct the Wasmtime host state
    let host_state = HostState {
        spi_ctx: SpiCtx {
            table: ResourceTable::new(),
            hardware: spi_hardware, // Only pass our new unified vector!
        },
        gpio_ctx: GpioCtx { pins: gpio_map },
        delay_ctx: DelayCtx {
            delay: alloc::boxed::Box::new(Delay),
        },
    };

    let mut store = Store::new(&engine, host_state);
    let mut linker = Linker::new(&engine);

    spi::add_to_linker(&mut linker).unwrap();
    gpio::add_to_linker(&mut linker).unwrap();
    delay::add_to_linker(&mut linker).unwrap();
    my::debug::logging::add_to_linker::<HostState, HasSelf<HostState>>(&mut linker, |state| state)
        .unwrap();

    let guest_bytes = include_bytes!("guest.pulley");
    info!(
        "Deserializing component (Size: {} bytes)...",
        guest_bytes.len()
    );

    let component = unsafe { Component::deserialize(&engine, guest_bytes) }.unwrap();

    info!("Instantiating...");
    let app = App::instantiate(&mut store, &component, &linker).unwrap();

    info!("Starting guest...");
    app.call_run(&mut store).unwrap();
>>>>>>> pico/main
}
