package wasi:spi;

interface spi {
    variant error {
        overrun,
        mode-fault,
        frame-format,
        chip-select-fault,

        other(string),
    }

    variant operation {
        read(u64),
        write(list<u8>),
        transfer(list<u8>),
        delay-ns(u32),
    }
    
    variant operation-result {
        read(list<u8>),
        write,
        transfer(list<u8>),
        delay,
    }

    resource spi-device {
        read: func(len: u64) -> result<list<u8>, error>;
        write: func(data: list<u8>) -> result<_, error>;
        transfer: func(data: list<u8>) -> result<list<u8>, error>;
        transaction: func(operations: list<operation>) -> result<list<operation-result>, error>;
    }

    get-devices: func() -> result<list<tuple<string, spi-device>>, error>;
}

world wasi-spi-host {
    import spi;
}
