package wasi:spi;

interface spi {

    // Errors as per https://docs.rs/embedded-hal/1.0.0/embedded_hal/spi/enum.ErrorKind.html
    variant error {
        overrun,
        mode-fault,
        frame-format,
        chip-select-fault,

        other(string),
    }

    // Operations as per https://docs.rs/embedded-hal/latest/embedded_hal/spi/enum.Operation.html
    // Transfer in place is not supported due to the pass-by-value semantics of the Component Model canonical ABI
    variant operation {
        read(u64),
        write(list<u8>),
        transfer(list<u8>),
        delay-ns(u32),
    }
    
    variant operation-result {
        read(list<u8>),
        write,
        transfer(list<u8>),
        delay,
    }

    resource spi-device {
        read: func(len: u64) -> result<list<u8>, error>;
        write: func(data: list<u8>) -> result<_, error>;
        transfer: func(data: list<u8>) -> result<list<u8>, error>;
        transaction: func(operations: list<operation>) -> result<list<operation-result>, error>;
    }

    open: func(name: string) -> result<spi-device, error>;
}

world wasi-spi-host {
    import spi;
}
