[wasi]

# Data/Command Pin
[[wasi.gpio]]
vlabel = "DC"
plabel = "GPIO22"
modes = ["digital-output"]

# Reset Pin
[[wasi.gpio]]
vlabel = "RES"
plabel = "GPIO23"
modes = ["digital-output"]

# Battery Voltage Control
[[wasi.gpio]]
vlabel = "VBATC"
plabel = "GPIO24"
modes = ["digital-output"]

# Logic Voltage Control
[[wasi.gpio]]
vlabel = "VDDC"
plabel = "GPIO25"
modes = ["digital-output"]

# The pmod-oled screen
[[wasi.spi]]
physical_path = "/dev/spidev0.0"
virtual_name = "screen"
